config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets
  root to: 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :tickets

  validates :artist, presence: true
  validates :location, presence: true
  validates :price_low, presence: true, numericality: {greater_than: 0}
  validates :price_high, presence: true, numericality: {greater_than: 0}
  validates :event_date, presence: true
  validate :event_date_not_from_past, :max_price_lower_than_min

  def event_date_not_from_past
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, 'cannot be in past')
    end
  end

  def max_price_lower_than_min
    if price_high.present? && price_low.present? && price_high < price_low
      errors.add(:price_high, 'cannot lower then low')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :event
  belongs_to :user

  validates :name, presence: true, length: {minimum: 6}
  validates :email_address, presence: true
  validates :price, presence: true
  validate :valid_price

  def valid_price
    if price.present? && event.present? && price > event.price_high
      errors.add(:price, "Price higher than allowed in this event (#{event.price_high})")
    end
    if price.present? && event.present? && price < event.price_low
      errors.add(:price, "Price lower than allowed in this event (#{event.price_low})")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_logged_in, only: [:new, :create]

  def show
    @event = Event.find(params[:id])
    @latLong = Geocoder.search(@event.location).first
    if @latLong
      @latLong = @latLong.coordinates
    end
    if @latLong.nil?
      @latLong = 0;
    end
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    event_params = params.require(:event).permit(:artist, :description, :location, :price_low, :price_high, :event_date)
    @event = Event.new(event_params)
    if @event.save
      redirect_to "/events/#{@event.id}", notice: 'Event was successfully created.'
    else
      render 'new'
    end
  end

  private

  def check_logged_in
    authenticate_or_request_with_http_basic('Ads') do |username, password|
      username == 'admin' && password == 'admin'
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(:email_address => current_user.email)
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html {redirect_to @ticket, notice: 'Ticket was successfully created.'}
        format.json {render :show, status: :created, location: @ticket}
      else
        format.html {render :new}
        format.json {render json: @ticket.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html {redirect_to @ticket, notice: 'Ticket was successfully updated.'}
        format.json {render :show, status: :ok, location: @ticket}
      else
        format.html {render :edit}
        format.json {render json: @ticket.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html {redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
  end

  def correct_user
    @ticket = current_user.tickets.find_by(id: params[:id])
    redirect_to tickets_path, notice: 'No permissions to edit this ticket' if @ticket.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-3">New event</h2>
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-12">
        <%= form_with(model: event, local: true) do |form| %>
          <% if event.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <ul class="mb-0">
                <% event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :artist %>
            <%= form.text_field :artist, :class => 'form-control', :placeholder => 'Artist' %>
          </div>

          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, :class => 'form-control', :placeholder => 'Enter description' %>
          </div>

          <div class="form-group">
            <%= form.label :location %>
            <%= form.text_field :location, :class => 'form-control', :placeholder => 'Enter event location' %>
          </div>

          <div class="form-group">
            <%= form.label 'Min price' %>
            <%= form.text_field :price_low, :class => 'form-control', :placeholder => 'Enter min price' %>
          </div>

          <div class="form-group">
            <%= form.label 'Max price' %>
            <%= form.text_field :price_high, :class => 'form-control', :placeholder => 'Enter max price' %>
          </div>

          <div class="form-group">
            <%= form.label :event_date %>
            <%= form.text_field :event_date, :class => 'form-control', :placeholder => 'Enter event date' %>
          </div>

          <%= form.submit :class => 'btn btn-primary' %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/events/_list.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-3">All events</h2>

    <div class="row">
      <table class="table table-hover events-table">
        <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Artist</th>
          <th scope="col">Location</th>
          <th scope="col">Lowest price</th>
          <th scope="col">Highest price</th>
          <th scope="col">Date</th>
          <th colspan="1"></th>
        </tr>
        </thead>
        <tbody>

        <% events.each do |event| %>
          <tr>
            <td><a href="/events/<%= event.id %>"><%= event.id %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.artist %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.location %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.price_low %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.price_high %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.event_date %></a></td>
            <td>
              <button onclick="$('#ticket_event_id').val('<%= event.id %>');"
                      class="btn btn-primary">Choose</button>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-0">All events</h2>
    <hr class="star-dark mb-5">

    <div class="row">
      <a href="<%= new_event_path %>" class="btn btn-primary btn-xl ml-auto">New event</a>
      <table class="table table-hover events-table">
        <thead>
        <tr>
          <th scope="col">Artist</th>
          <th scope="col">Location</th>
          <th scope="col">Date</th>
        </tr>
        </thead>
        <tbody>
        <% @events.each {|event| %>
          <tr>
            <td><a href="/events/<%= event.id %>"><%= event.artist %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.location %></a></td>
            <td><a href="/events/<%= event.id %>"><%= event.event_date %></a></td>
          </tr>
        <% } %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-0"><%= @event.artist %></h2>
    <hr class="star-dark mb-5">

    <div class="row">
      <div class="col-md-6 text-center">
        <div class="mb-3">
          <span class="question">Who?</span>
          <div>
            <strong><%= @event.artist %></strong>
          </div>
        </div>
        <div class="mb-3">
          <span class="question">Where?</span>
          <div>
            <strong><%= @event.location %></strong>
          </div>
        </div>
        <div>
          <span class="question">What?</span>
          <div>
            <strong><%= @event.description %></strong>
          </div>
        </div>
      </div>
      <div class="col-md-6 text-center">
        <div class="mb-3">
          <span class="question">How much?</span>
          <div>
            <strong><%= number_with_precision(@event.price_low, :precision => 2) %>
              -  <%= number_with_precision(@event.price_high, :precision => 2) %></strong>
          </div>
        </div>
        <div>
          <span class="question">When?</span>
          <div>
            <strong><%= @event.event_date %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<div style="height: 70vh;" id="events-map"></div>
<script>
    var eventMap = L.map('events-map');
    var mapboxToken = 'pk.eyJ1Ijoid29qdGFzNjI2IiwiYSI6ImNqcjg2MXhlczAyd20zeXF4cGxmenp1bGEifQ.Sxyfr4VMLK9Eq5R6M2deHw';
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=' + mapboxToken, {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: mapboxToken
    }).addTo(eventMap);
    var latLongArray = <%= @latLong %>;
    if (latLongArray) {
        eventMap.setView(latLongArray, 15);
        L.marker(latLongArray).addTo(eventMap);
    } else {
        var cracowCenter = [50.062201, 19.938157];
        eventMap.setView(cracowCenter, 15);
    }
</script>

<% if current_user.present? %>
  <%= render "tickets/new_ticket_form",
             ticket: Ticket.new(:event_id => @event.id, :email_address => current_user.email),
             show_event_id: false,
             edit_form: false %>
<% end %>

<%= render "tickets/list", tickets: @event.tickets, show_new_ticket_btn: false %>

app/views/index/index.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-0">Events database and ticket sale</h2>
    <hr class="star-dark mb-5">

    <div class="row">
      <div class="col-md-6">
        <a class="portfolio-item d-block mx-auto square-link rounded"
           href="/events">
          <div class="square-link_element h-100 d-flex justify-content-center align-items-center">
            <h2>EVENTS</h2>
          </div>
        </a>
      </div>
      <div class="col-md-6">
        <a class="portfolio-item d-block mx-auto square-link rounded"
           href="/tickets">
          <div class="square-link_element h-100 d-flex justify-content-center align-items-center">
            <h2>TICKETS</h2>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>El Billete</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if notice %>
  <p class="alert alert-success mb-0"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger mb-0"><%= alert %></p>
<% end %>

<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="/">El Billete</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded"
            type="button" data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-0 mx-lg-1">
          <a class="nav-link py-3 px-0 px-lg-3 rounded" href="/events">Events</a>
        </li>
        <li class="nav-item mx-0 mx-lg-1">
          <a class="nav-link py-3 px-0 px-lg-3 rounded" href="/tickets">Tickets</a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item mx-0 mx-lg-1">
            <%= link_to 'Edit profile', edit_user_registration_path,
                        :class => 'nav-link py-3 px-0 px-lg-3 rounded' %>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <%= link_to "Logout", destroy_user_session_path, method: :delete,
                        :class => 'nav-link py-3 px-0 px-lg-3 rounded logout-link' %>
            <span class="user-email font-weight-normal text-white-50">(<%= current_user.email %>)</span>
          </li>
        <% else %>
          <li class="nav-item mx-0 mx-lg-1">
            <%= link_to "Sign up", new_user_registration_path,
                        :class => 'nav-link py-3 px-0 px-lg-3 rounded' %>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <%= link_to "Log in", new_user_session_path,
                        :class => 'nav-link py-3 px-0 px-lg-3 rounded' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_list.html.erb
<section>
  <div class="container">
    <h3 class="text-center text-uppercase text-secondary mb-0">Tickets</h3>

    <div class="row">
      <% if show_new_ticket_btn %>
        <a href="<%= new_ticket_path %>" class="btn btn-primary btn-xl ml-auto">New ticket</a>
      <% end %>
      <table class="table table-hover events-table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Seat id</th>
          <th>Price</th>
          <th>Email address</th>
          <th>Address</th>
          <th>Phone</th>
          <th colspan="2"></th>
        </tr>
        </thead>
        <tbody>
        <% tickets.each do |ticket| %>
          <tr>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.name %></a></td>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.seat_id_seq %></a></td>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.price %></a></td>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.email_address %></a></td>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.address %></a></td>
            <td><a href="/tickets/<%= ticket.id %>"><%= ticket.phone %></a></td>
            <% if ticket.user == current_user %>
              <td><%= link_to 'Edit', edit_ticket_path(ticket), :class => 'btn btn-primary ml-auto mr-2' %></td>
              <td><%= link_to 'Remove', ticket, method: :delete, data: {confirm: 'Are you sure?'},
                              :class => 'btn btn-primary ml-auto' %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/tickets/_new_ticket_form.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-3">
      <% if edit_form %>
        Edit ticket
      <% else %>
        New ticket
      <% end %>
    </h2>
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-12">
        <%= form_with(model: ticket, local: true) do |form| %>
          <% if ticket.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <ul class="mb-0">
                <% ticket.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <% if show_event_id %>
            <div class="form-group">
              <%= form.label 'Event id' %>
              <%= form.text_field :event_id, :class => 'form-control', :placeholder => 'Enter event ID' %>
            </div>
          <% else %>
            <%= form.hidden_field :event_id %>
          <% end %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, :class => 'form-control', :placeholder => 'Enter your name' %>
          </div>

          <div class="form-group">
            <%= form.label :seat_id_seq %>
            <%= form.text_field :seat_id_seq, :class => 'form-control', :placeholder => 'Enter seat ID' %>
          </div>

          <div class="form-group">
            <%= form.label :address %>
            <%= form.text_field :address, :class => 'form-control', :placeholder => 'Enter your Address' %>
          </div>

          <div class="form-group">
            <%= form.label :price %>
            <%= form.text_field :price, :class => 'form-control', :placeholder => 'Enter ticket price' %>
          </div>

          <div class="form-group">
            <%= form.label 'Email' %>
            <%= form.text_field :email_address, :class => 'form-control', :placeholder => 'Enter your email',
                                :type => 'email' %>
          </div>

          <div class="form-group">
            <%= form.label :phone %>
            <%= form.text_field :phone, :class => 'form-control', :placeholder => 'Enter your phone number' %>
          </div>

          <%= form.submit :class => 'btn btn-primary' %>
          <% if edit_form %>
            <%= link_to 'Show ticket', @ticket, :class => 'btn btn-primary float-right' %>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/tickets/_tickets_list.html.erb
<h1>Tickets</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Seat id seq</th>
    <th>Address</th>
    <th>Price</th>
    <th>Email address</th>
    <th>Phone</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.name %></td>
      <td><%= ticket.seat_id_seq %></td>
      <td><%= ticket.address %></td>
      <td><%= ticket.price %></td>
      <td><%= ticket.email_address %></td>
      <td><%= ticket.phone %></td>
      <td><%= link_to 'Show', ticket %></td>
      <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
      <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<%= render 'new_ticket_form', ticket: @ticket, show_event_id: true, edit_form: true %>
<%= render 'events/list', events: Event.all %>

app/views/tickets/index.html.erb
<%= render 'list', tickets: @tickets, show_new_ticket_btn: true %>

app/views/tickets/new.html.erb
<%= render 'new_ticket_form', ticket: @ticket, show_event_id: true, edit_form: false %>
<%= render 'events/list', events: Event.all %>

app/views/tickets/show.html.erb
<section>
  <div class="container">
    <h2 class="text-center text-uppercase text-secondary mb-0">Event ticket</h2>
    <hr class="star-dark mb-5">

    <div class="row">
      <div class="col-md-6 text-center">
        <h4>Ticket</h4>
        <p>
          <span>Event:</span>
          <a href="/events/<%= @ticket.event.id %>"><strong><%= @ticket.event.artist %></strong></a>
        </p>
        <p>
          <span>Seat id:</span>
          <strong><%= @ticket.seat_id_seq %></strong>
        </p>
        <p>
          <span>Price:</span>
          <strong><%= @ticket.price %></strong>
        </p>
      </div>
      <div class="col-md-6 text-center">
        <h4>Owner</h4>
        <p>
          <span>Name:</span>
          <strong><%= @ticket.name %></strong>
        </p>
        <p>
          <span>Address:</span>
          <strong><%= @ticket.address %></strong>
        </p>
        <p>
          <span>Email:</span>
          <strong><%= @ticket.email_address %></strong>
        </p>
        <p>
          <span>Phone:</span>
          <strong><%= @ticket.phone %></strong>
        </p>
      </div>
      <div class="col-md-12 text-center mt-4" style="min-width: 10rem;">
        <% if @ticket.user == current_user %>
          <%= link_to 'Edit', edit_ticket_path(@ticket), :class => 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</section>